#!/bin/bash

yum install -y docker

# Start Docker service
systemctl enable docker
systemctl start docker

# Pull Docker images
docker pull yulianbortsov/backend
docker pull yulianbortsov/frontend

# Create Docker network
docker network create netflix-network

# Run containers
docker run -d --name movie-catalog --network netflix-network -p 8080:8080 yulianbortsov/backend
docker run -d --name frontend --network netflix-network -p 3000:3000 -e MOVIE_CATALOG_SERVICE=http://movie-catalog:8080 yulianbortsov/frontend
