#!/bin/bash

yum install -y docker

# Start Docker service
systemctl enable docker
systemctl start docker

# Pull Docker images
docker pull orikerbis/movie-catalog
docker pull orikerbis/frontend

# Create Docker network
docker network create netflix-network

# Run containers
docker run -d --name movie-catalog --network netflix-network -p 8080:8080 orikerbis/movie-catalog
docker run -d --name frontend --network netflix-network -p 3000:3000 orikerbis/frontend
