#!/bin/bash 

yum install docker
docker pull orikerbis/movie-catalog
docker pull orikerbis/frontend
docker network create netflix-network
docker run -d --name movie-catalog --network netflix-network -p 8080:8080 movie-catalog
docker run -d --name frontend --network netflix-network -p 3000:3000 frontend

